### ISSUE TITLE
v4 STL Dimensions?

### ISSUE THREAD

**Issue by aakoch** [LucidVR/lucidgloves#63]
Something is off. It might be me, I admit. But when I put the STLs in 2 different programs, it doesn't look like the dimensions would work. When I laid out the green pot sliders with the rigid mount, the sliders would occupy the same space:
![image](https://user-images.githubusercontent.com/137713/159857239-ce44517e-8394-4810-ad19-1d643e155d88.png)

And they look too long:
![image](https://user-images.githubusercontent.com/137713/159858210-882f3658-e720-4f4d-8d28-58a1cd238d74.png)

But where they actually slide together (height and width) looks correct.

Am I crazy?

**Comment by lucas-vrtech** [comment]
Heyo, that's a really good question. The reason that the sliders look too close together is because in practice, the RigidMount is curved, not straight (that's why it needs to be thin enough to be flexible). 

![Example](https://cdn.discordapp.com/attachments/790676300552994826/956559229785899018/A2BED9E0-5F59-4A54-B770-5C0E07EC0123.jpg)

As for the length part, that's intentionally done that way so that the locking mechanism for the slide works in both directions.
